### ISSUE TITLE
Sub-dicts with falsy value can be lost

### ISSUE THREAD

**Issue by bmerry** [mewwts/addict#88]
In 2.0.0:
```python
>>> from addict import Dict
>>> a[0].x = 1
>>> print(a)
{}
```
This is because [this line](https://github.com/mewwts/addict/blob/master/addict/addict.py#L38) tests for `key` being true, for no good reason that I can see.

**Comment by mewwts** [comment]
This should now be fixed 🥇

**Comment by bmerry** [comment]
Looking at the code, I suspect `a[None].x = 1` will still fail. I'm not seeing why the `key is not None` test is needed at all.

**Comment by mewwts** [comment]
You're right! In my head `None` was unhashable, but it's not. Editing....
